INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GNURADIO_YUNSDR gnuradio-yunsdr)

FIND_PATH(
	GNURADIO_YUNSDR_INCLUDE_DIRS
    NAMES gnuradio/yunsdr/api.h
    HINTS $ENV{GNURADIO_YUNSDR_DIR}/include
        ${PC_GNURADIO_YUNSDR_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
          ${GNURADIO_INSTALL_PREFIX}/include
)

FIND_LIBRARY(
    GNURADIO_YUNSDR_LIBRARIES
    NAMES gnuradio-yunsdr
    HINTS $ENV{GNURADIO_YUNSDR_DIR}/lib
        ${PC_GNURADIO_YUNSDR_LIBDIR}
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          ${GNURADIO_INSTALL_PREFIX}/lib
)

if(GNURADIO_YUNSDR_INCLUDE_DIRS AND GNURADIO_YUNSDR_LIBRARIES)
  set(GNURADIO_YUNSDR_FOUND TRUE CACHE INTERNAL "gnuradio-yunsdr found")
  message(STATUS "Found gnuradio-yunsdr: ${GNURADIO_YUNSDR_INCLUDE_DIRS}, ${GNURADIO_YUNSDR_LIBRARIES}")
else(GNURADIO_YUNSDR_INCLUDE_DIRS AND GNURADIO_YUNSDR_LIBRARIES)
  set(GNURADIO_YUNSDR_FOUND FALSE CACHE INTERNAL "gnuradio-yunsdr found")
  message(STATUS "gnuradio-yunsdr not found.")
endif(GNURADIO_YUNSDR_INCLUDE_DIRS AND GNURADIO_YUNSDR_LIBRARIES)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GNURADIO_YUNSDR DEFAULT_MSG GNURADIO_YUNSDR_LIBRARIES GNURADIO_YUNSDR_INCLUDE_DIRS)
MARK_AS_ADVANCED(GNURADIO_YUNSDR_LIBRARIES GNURADIO_YUNSDR_INCLUDE_DIRS)
